version: "3"
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysqlapp
    container_name: "quiz_mysql_db"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=quiz_db
    ports:
      - "3306:3306"
  web:
    build: "./apache"
    container_name: "quiz_web"
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
      - 5000:5000
    volumes:
      - "./html:/var/www/html"
      - "./apache/flask:/usr/src/app"
    privileged: true
    command: flask run --host 0.0.0.0 --port 5000