version: "3"
networks:
  app-net:
    driver: bridge
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysqlapp
    container_name: "quiz_mysql_db"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=quiz_db
    networks:
      - app-net
    ports:
      - "3306:3306"
  web:
    build: ./web
    container_name: "quiz_web"
    environment:
      TZ: Asia/Tokyo
    networks:
      - app-net
    ports:
      - 8080:80
    volumes:
      - ./web:/usr/src/app
    privileged: true
  api:
    build: ./flask
    container_name: "quiz_api"
    environment:
      TZ: Asia/Tokyo
    networks:
      - app-net
    ports:
      - 5000:5000
    volumes:
      - ./flask:/usr/src/app
    privileged: true
    command: flask run --host 0.0.0.0 --port 5000