version: "3"
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysqlapp
    container_name: "quiz_mysql_db"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=quiz_db
      - LC_ALL=ja_JP.UTF-8
      - LANG=ja_JP.UTF-8
    ports:
      - "3306:3306"