USE quiz_db;
ALTER TABLE aws_quiz ADD COLUMN checked BOOLEAN DEFAULT 0;
ALTER TABLE applied ADD COLUMN checked BOOLEAN DEFAULT 0;
ALTER TABLE lpic ADD COLUMN checked BOOLEAN DEFAULT 0;
ALTER TABLE english_speaking ADD COLUMN checked BOOLEAN DEFAULT 0;
