USE quiz_db;
ALTER TABLE aws_quiz ADD COLUMN deleted BOOLEAN DEFAULT 0;
ALTER TABLE applied ADD COLUMN deleted BOOLEAN DEFAULT 0;
ALTER TABLE lpic ADD COLUMN deleted BOOLEAN DEFAULT 0;
ALTER TABLE english_speaking ADD COLUMN deleted BOOLEAN DEFAULT 0;
